# Default values for bruno-site
# This is a YAML-formatted file.

# Domain configuration
domain: "lucena.cloud"

replicaCount: 1

imagePullSecrets:
  - name: ghcr-secret
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

# API Configuration
api:
  image:
    repository: ghcr.io/brunovlucena/bruno-site/api
    pullPolicy: IfNotPresent
    tag: "latest"
  service:
    type: ClusterIP
    port: 8080
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

# Frontend Configuration
frontend:
  image:
    repository: ghcr.io/brunovlucena/bruno-site/frontend
    pullPolicy: IfNotPresent
    tag: "latest"
  service:
    type: ClusterIP
    port: 80
  appEnv: "production"
  resources:
    limits:
      cpu: 300m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - host: lucena.cloud
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: bruno-site-tls
      hosts:
        - lucena.cloud

autoscaling:
  enabled: true
  minReplicas: 1 
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# CORS Configuration
corsOrigin: "https://lucena.cloud"

# Database configuration
database:
  enabled: true
  type: postgresql
  host: bruno-site-postgres
  port: 5432
  name: bruno_site
  user: postgres
  password: ""
  existingSecret: ""

# PostgreSQL configuration
postgres:
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  persistence:
    enabled: true
    size: 8Gi
    storageClass: ""

# Redis configuration
redis:
  enabled: true
  host: bruno-site-redis
  port: 6379
  password: ""
  existingSecret: ""
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  persistence:
    enabled: true
    size: 2Gi
    storageClass: ""

# Secrets
secrets:
  databasePassword: "bruno123"
  redisPassword: ""
