# Dependabot configuration for Bruno Site
# This file configures automatic dependency updates and security monitoring

version: 2
updates:
  # Go dependencies (API)
  - package-ecosystem: "gomod"
    directory: "/api"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "brunovlucena"
    assignees:
      - "brunovlucena"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "go"
      - "security"
    ignore:
      # Ignore major version updates that might break compatibility
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Node.js dependencies (Frontend)
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "brunovlucena"
    assignees:
      - "brunovlucena"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "javascript"
      - "security"
    ignore:
      # Ignore major version updates that might break compatibility
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "brunovlucena"
    assignees:
      - "brunovlucena"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
      - "security"
    ignore:
      # Ignore major version updates that might break compatibility
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "brunovlucena"
    assignees:
      - "brunovlucena"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
      - "security"

  # Security updates (critical and high severity)
  - package-ecosystem: "gomod"
    directory: "/api"
    schedule:
      interval: "daily"
      time: "06:00"
    open-pull-requests-limit: 5
    reviewers:
      - "brunovlucena"
    assignees:
      - "brunovlucena"
    commit-message:
      prefix: "security"
      include: "scope"
    labels:
      - "security"
      - "critical"
      - "go"
    # Only update for security vulnerabilities
    allow:
      - dependency-type: "direct"
        update-type: "security"
      - dependency-type: "indirect"
        update-type: "security"

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
      time: "06:00"
    open-pull-requests-limit: 5
    reviewers:
      - "brunovlucena"
    assignees:
      - "brunovlucena"
    commit-message:
      prefix: "security"
      include: "scope"
    labels:
      - "security"
      - "critical"
      - "javascript"
    # Only update for security vulnerabilities
    allow:
      - dependency-type: "direct"
        update-type: "security"
      - dependency-type: "indirect"
        update-type: "security"
