{{- if .Values.database.enabled }}
# =============================================================================
# 🗄️ DATABASE MIGRATIONS CONFIGMAP
# =============================================================================
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bruno-site.fullname" . }}-migrations
  labels:
    {{- include "bruno-site.labels" . | nindent 4 }}
    app.kubernetes.io/component: db-migrations
data:
  001_complete_schema.sql: |-
{{ .Files.Get "api/migrations/001_complete_schema.sql" | nindent 4 }}

---
# =============================================================================
# 🚀 DATABASE INITIALIZATION JOB
# =============================================================================
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "bruno-site.fullname" . }}-db-init
  labels:
    {{- include "bruno-site.labels" . | nindent 4 }}
    app.kubernetes.io/component: db-init
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "10"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      labels:
        {{- include "bruno-site.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: db-init
    spec:
      restartPolicy: Never
      containers:
        - name: db-init
          image: postgres:16-alpine
          command:
            - /bin/sh
            - -c
            - |
              echo "🗄️ Waiting for PostgreSQL to be ready..."
              until pg_isready -h {{ include "bruno-site.fullname" . }}-postgres -p {{ .Values.database.port }} -U {{ .Values.database.user }}; do
                echo "⏳ PostgreSQL is not ready yet. Waiting..."
                sleep 2
              done
              echo "✅ PostgreSQL is ready. Running migrations..."
              
              # Run complete schema migration
              echo "🔄 Running 001_complete_schema.sql..."
              psql -h {{ include "bruno-site.fullname" . }}-postgres -p {{ .Values.database.port }} -U {{ .Values.database.user }} -d {{ .Values.database.name }} -f /migrations/001_complete_schema.sql
              
              echo "✅ Database initialization completed successfully!"
          env:
            - name: PGPASSWORD
              {{- if .Values.database.existingSecret }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.existingSecret }}
                  key: password
              {{- else if .Values.secrets.databasePassword }}
              value: {{ .Values.secrets.databasePassword | quote }}
              {{- else }}
              valueFrom:
                secretKeyRef:
                  name: {{ include "bruno-site.fullname" . }}-db-secret
                  key: password
              {{- end }}
          volumeMounts:
            - name: migrations
              mountPath: /migrations
              readOnly: true
      volumes:
        - name: migrations
          configMap:
            name: {{ include "bruno-site.fullname" . }}-migrations
{{- end }}
