# ConfigMap for portfolio configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: portfolio-config
  namespace: {{ .Values.namespaces.portfolio.name }}
data:
  db_host: {{ .Values.config.database.host | quote }}
  db_port: {{ .Values.config.database.port | quote }}
  db_name: {{ .Values.config.database.name | quote }}
  redis_host: {{ .Values.config.redis.host | quote }}
  redis_port: {{ .Values.config.redis.port | quote }}
  redis_db: {{ .Values.config.redis.db | quote }}
---
# Secrets for sensitive data
apiVersion: v1
kind: Secret
metadata:
  name: portfolio-secrets
  namespace: {{ .Values.namespaces.portfolio.name }}
type: Opaque
data:
  db_user: {{ .Values.secrets.database.user | b64enc | quote }}
  db_password: {{ .Values.secrets.database.password | b64enc | quote }}
  jwt_secret: {{ .Values.secrets.jwt.secret | b64enc | quote }}
  redis_password: {{ .Values.secrets.redis.password | b64enc | quote }}
---

