name: Build and Push Docker Images

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      force_rebuild:
        description: 'Force rebuild (skip cache)'
        required: false
        default: 'false'
        type: boolean
      build_api:
        description: 'Build API image'
        required: false
        default: 'true'
        type: boolean
      build_frontend:
        description: 'Build Frontend image'
        required: false
        default: 'true'
        type: boolean

jobs:
  build-api:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.build_api == 'true')
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push API image
        uses: docker/build-push-action@v5
        with:
          context: ./api
          file: ./api/Dockerfile
          push: true
          no-cache: ${{ github.event.inputs.force_rebuild == 'true' }}
          tags: ghcr.io/${{ github.repository }}-api:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64

      - name: Output API image tags
        run: |
          echo "✅ API image built and pushed successfully!"
          echo "Tags: ghcr.io/${{ github.repository }}-api:latest"

  build-frontend:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.build_frontend == 'true')
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          no-cache: ${{ github.event.inputs.force_rebuild == 'true' }}
          tags: ghcr.io/${{ github.repository }}-frontend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64

      - name: Output Frontend image tags
        run: |
          echo "✅ Frontend image built and pushed successfully!"
          echo "Tags: ghcr.io/${{ github.repository }}-frontend:latest"

