name: Package Helm Chart

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Validate Helm Chart
        run: |
          echo "🔍 Validating Helm chart..."
          helm lint chart/
          
      - name: Package Helm Chart
        run: |
          echo "📦 Packaging Helm chart..."
          helm package chart/ --debug
          
          # Display chart info
          CHART_VERSION=$(grep '^version:' chart/Chart.yaml | awk '{print $2}')
          CHART_NAME=$(grep '^name:' chart/Chart.yaml | awk '{print $2}')
          echo "✅ Successfully packaged $CHART_NAME v$CHART_VERSION"
          
          # List generated files
          ls -la *.tgz

      - name: Upload Chart Artifact
        uses: actions/upload-artifact@v4
        with:
          name: helm-chart
          path: '*.tgz'
          retention-days: 30
